### ISSUE TITLE
Resolve Dependabot alerts

### ISSUE THREAD

**Issue by mrfatguy** [the-jamb/gps-protect#26]
After last push we have received info about three Dependabot alerts:

    GitHub found 3 vulnerabilities on the-jamb/gps-protect's default branch (3 moderate).
    To find out more, visit: https://github.com/the-jamb/gps-protect/security/dependabot

The list contains:

- [PR #24](https://github.com/the-jamb/gps-protect/pull/24): [Follow Redirects' Proxy-Authorization header kept across hosts](https://github.com/the-jamb/gps-protect/security/dependabot/5)
- [PR #24](https://github.com/the-jamb/gps-protect/pull/24): [Follow Redirects improperly handles URLs in the url.parse() function ](https://github.com/the-jamb/gps-protect/security/dependabot/1)
- [PR #20](https://github.com/the-jamb/gps-protect/pull/20): [NPM IP package incorrectly identifies some private IP addresses as public ](https://github.com/the-jamb/gps-protect/security/dependabot/4)

Please, fix them. Thank you.

**Comment by MadejaMaciej** [comment]
After investigating, can be safely closed
